clear

echo "                                                                         "
echo "                                                                         "
echo "                                                                         "
echo "                                     ▄▄▄      ▓█████▄  ███▄ ▄███▓ ▄▄▄     ▄▄▄█████▓"
echo "                                    ▒████▄    ▒██▀ ██▌▓██▒▀█▀ ██▒▒████▄   ▓  ██▒ ▓▒"
echo "                                    ▒██  ▀█▄  ░██   █▌▓██    ▓██░▒██  ▀█▄ ▒ ▓██░ ▒░"
echo "                                    ░██▄▄▄▄██ ░▓█▄   ▌▒██    ▒██ ░██▄▄▄▄██░ ▓██▓ ░ "
echo "                                     ▓█   ▓██▒░▒████▓ ▒██▒   ░██▒ ▓█   ▓██▒ ▒██▒ ░ "
echo "                                     ▒▒   ▓▒█░ ▒▒▓  ▒ ░ ▒░   ░  ░ ▒▒   ▓▒█░ ▒ ░░ "
echo "                                     ▒   ▒▒ ░ ░ ▒  ▒ ░  ░      ░  ▒   ▒▒ ░   ░  "
echo "                                    ░   ▒    ░ ░  ░ ░      ░     ░   ▒    ░   "
echo "                                        ░  ░   ░           ░         ░  ░   "
echo "                                             ░     "





python3 /home/ubuntu/Desktop/servante/A.py &
python3 /home/ubuntu/Desktop/servante/AA.py &
python3 /home/ubuntu/Desktop/servante/AAC.py &
python3 /home/ubuntu/Desktop/servante/AACG.py &
python3 /home/ubuntu/Desktop/servante/AACI.py &
python3 /home/ubuntu/Desktop/servante/AACIU.py &
python3 /home/ubuntu/Desktop/servante/AACIW.py &
python3 /home/ubuntu/Desktop/servante/AADI.py &
python3 /home/ubuntu/Desktop/servante/AAIC.py &
python3 /home/ubuntu/Desktop/servante/AAL.py &
python3 /home/ubuntu/Desktop/servante/AAMC.py &
python3 /home/ubuntu/Desktop/servante/AAME.py &
python3 /home/ubuntu/Desktop/servante/AAN.py &
python3 /home/ubuntu/Desktop/servante/AAOI.py &
python3 /home/ubuntu/Desktop/servante/AAON.py &
python3 /home/ubuntu/Desktop/servante/AAP.py &
python3 /home/ubuntu/Desktop/servante/AAPL.py &
python3 /home/ubuntu/Desktop/servante/AAQC.py &
python3 /home/ubuntu/Desktop/servante/AAT.py &
python3 /home/ubuntu/Desktop/servante/AATC.py &
python3 /home/ubuntu/Desktop/servante/AAU.py &
python3 /home/ubuntu/Desktop/servante/AAWW.py &
python3 /home/ubuntu/Desktop/servante/AB.py &
python3 /home/ubuntu/Desktop/servante/ABB.py &
python3 /home/ubuntu/Desktop/servante/ABBV.py &
python3 /home/ubuntu/Desktop/servante/ABC.py &
python3 /home/ubuntu/Desktop/servante/ABCB.py &
python3 /home/ubuntu/Desktop/servante/ABCL.py &
python3 /home/ubuntu/Desktop/servante/ABCM.py &
python3 /home/ubuntu/Desktop/servante/ABEO.py &
python3 /home/ubuntu/Desktop/servante/ABEV.py &
python3 /home/ubuntu/Desktop/servante/ABG.py &
python3 /home/ubuntu/Desktop/servante/ABGI.py &
python3 /home/ubuntu/Desktop/servante/ABIO.py &
python3 /home/ubuntu/Desktop/servante/ABM.py &
python3 /home/ubuntu/Desktop/servante/ABMD.py &
python3 /home/ubuntu/Desktop/servante/ABNB.py &
python3 /home/ubuntu/Desktop/servante/ABOS.py &
python3 /home/ubuntu/Desktop/servante/ABR.py &
python3 /home/ubuntu/Desktop/servante/ABSI.py &
python3 /home/ubuntu/Desktop/servante/ABST.py &
python3 /home/ubuntu/Desktop/servante/ABT.py &
python3 /home/ubuntu/Desktop/servante/ABTX.py &
python3 /home/ubuntu/Desktop/servante/ABUS.py &
python3 /home/ubuntu/Desktop/servante/ABVC.py &
python3 /home/ubuntu/Desktop/servante/AC.py &
python3 /home/ubuntu/Desktop/servante/ACA.py &
python3 /home/ubuntu/Desktop/servante/ACAB.py &
python3 /home/ubuntu/Desktop/servante/ACABU.py &
python3 /home/ubuntu/Desktop/servante/ACAD.py &
python3 /home/ubuntu/Desktop/servante/ACAH.py &
python3 /home/ubuntu/Desktop/servante/ACAHU.py &
python3 /home/ubuntu/Desktop/servante/ACAHW.py &
python3 /home/ubuntu/Desktop/servante/ACAQ.py &
python3 /home/ubuntu/Desktop/servante/ACAXR.py &
python3 /home/ubuntu/Desktop/servante/ACAXU.py &
python3 /home/ubuntu/Desktop/servante/ACAXW.py &
python3 /home/ubuntu/Desktop/servante/ACEL.py &
python3 /home/ubuntu/Desktop/servante/ACER.py &
python3 /home/ubuntu/Desktop/servante/ACET.py &
python3 /home/ubuntu/Desktop/servante/ACEV.py &
python3 /home/ubuntu/Desktop/servante/ACEVU.py &
python3 /home/ubuntu/Desktop/servante/ACGL.py &
python3 /home/ubuntu/Desktop/servante/ACGLN.py &
python3 /home/ubuntu/Desktop/servante/ACGLO.py &
python3 /home/ubuntu/Desktop/servante/ACH.py &
python3 /home/ubuntu/Desktop/servante/ACHC.py &
python3 /home/ubuntu/Desktop/servante/ACHL.py &
python3 /home/ubuntu/Desktop/servante/ACHR.py &
python3 /home/ubuntu/Desktop/servante/ACHV.py &
python3 /home/ubuntu/Desktop/servante/ACI.py &
python3 /home/ubuntu/Desktop/servante/ACII.py &
python3 /home/ubuntu/Desktop/servante/ACIU.py &
python3 /home/ubuntu/Desktop/servante/ACIW.py &
python3 /home/ubuntu/Desktop/servante/ACM.py &
python3 /home/ubuntu/Desktop/servante/ACMR.py &
python3 /home/ubuntu/Desktop/servante/ACN.py &
python3 /home/ubuntu/Desktop/servante/ACNB.py &
python3 /home/ubuntu/Desktop/servante/ACON.py &
python3 /home/ubuntu/Desktop/servante/ACONW.py &
python3 /home/ubuntu/Desktop/servante/ACOR.py &
python3 /home/ubuntu/Desktop/servante/ACP.py &
python3 /home/ubuntu/Desktop/servante/ACQR.py &
python3 /home/ubuntu/Desktop/servante/ACQRU.py &
python3 /home/ubuntu/Desktop/servante/ACR.py &
python3 /home/ubuntu/Desktop/servante/ACRO.py &
python3 /home/ubuntu/Desktop/servante/ACRS.py &
python3 /home/ubuntu/Desktop/servante/ACRX.py &
python3 /home/ubuntu/Desktop/servante/ACST.py &
python3 /home/ubuntu/Desktop/servante/ACT.py &
python3 /home/ubuntu/Desktop/servante/ACTD.py &
python3 /home/ubuntu/Desktop/servante/ACU.py &
python3 /home/ubuntu/Desktop/servante/ACV.py &
python3 /home/ubuntu/Desktop/servante/ACVA.py &
python3 /home/ubuntu/Desktop/servante/ACXP.py &
python3 /home/ubuntu/Desktop/servante/ADAG.py &
python3 /home/ubuntu/Desktop/servante/ADAL.py &
python3 /home/ubuntu/Desktop/servante/ADAP.py &
python3 /home/ubuntu/Desktop/servante/ADBE.py &
python3 /home/ubuntu/Desktop/servante/ADC.py &
python3 /home/ubuntu/Desktop/servante/ADCT.py &
python3 /home/ubuntu/Desktop/servante/ADER.py &
python3 /home/ubuntu/Desktop/servante/ADERW.py &
python3 /home/ubuntu/Desktop/servante/ADES.py &
python3 /home/ubuntu/Desktop/servante/ADEX.py &
python3 /home/ubuntu/Desktop/servante/ADGI.py &
python3 /home/ubuntu/Desktop/servante/ADI.py &
python3 /home/ubuntu/Desktop/servante/ADIL.py &
python3 /home/ubuntu/Desktop/servante/ADM.py &
python3 /home/ubuntu/Desktop/servante/ADMA.py &
python3 /home/ubuntu/Desktop/servante/ADMP.py &
python3 /home/ubuntu/Desktop/servante/ADN.py &
python3 /home/ubuntu/Desktop/servante/ADNT.py &
python3 /home/ubuntu/Desktop/servante/ADOC.py &
python3 /home/ubuntu/Desktop/servante/ADOCR.py &
python3 /home/ubuntu/Desktop/servante/ADOCW.py &
python3 /home/ubuntu/Desktop/servante/ADP.py &
python3 /home/ubuntu/Desktop/servante/ADPT.py &
python3 /home/ubuntu/Desktop/servante/ADRA.py &
python3 /home/ubuntu/Desktop/servante/ADRT.py &
python3 /home/ubuntu/Desktop/servante/ADSE.py &
python3 /home/ubuntu/Desktop/servante/ADSEW.py &
python3 /home/ubuntu/Desktop/servante/ADSK.py &
python3 /home/ubuntu/Desktop/servante/ADT.py &
python3 /home/ubuntu/Desktop/servante/ADTH.py &
python3 /home/ubuntu/Desktop/servante/ADTHW.py &
python3 /home/ubuntu/Desktop/servante/ADTN.py &
python3 /home/ubuntu/Desktop/servante/ADTX.py &
python3 /home/ubuntu/Desktop/servante/ADUS.py &
python3 /home/ubuntu/Desktop/servante/ADV.py &
python3 /home/ubuntu/Desktop/servante/ADVM.py &
python3 /home/ubuntu/Desktop/servante/ADX.py &
python3 /home/ubuntu/Desktop/servante/ADXN.py &
python3 /home/ubuntu/Desktop/servante/AE.py &
python3 /home/ubuntu/Desktop/servante/AEAC.py &
python3 /home/ubuntu/Desktop/servante/AEE.py &
python3 /home/ubuntu/Desktop/servante/AEF.py &
python3 /home/ubuntu/Desktop/servante/AEFC.py &
python3 /home/ubuntu/Desktop/servante/AEG.py &
python3 /home/ubuntu/Desktop/servante/AEI.py &
python3 /home/ubuntu/Desktop/servante/AEIS.py &
python3 /home/ubuntu/Desktop/servante/AEL.py &
python3 /home/ubuntu/Desktop/servante/AEM.py &
python3 /home/ubuntu/Desktop/servante/AEMD.py &
python3 /home/ubuntu/Desktop/servante/AENZ.py &
python3 /home/ubuntu/Desktop/servante/AEO.py &
python3 /home/ubuntu/Desktop/servante/AEP.py &
python3 /home/ubuntu/Desktop/servante/AEPPZ.py &
python3 /home/ubuntu/Desktop/servante/AER.py &
python3 /home/ubuntu/Desktop/servante/AERC.py &
python3 /home/ubuntu/Desktop/servante/AERI.py &
python3 /home/ubuntu/Desktop/servante/AES.py &
python3 /home/ubuntu/Desktop/servante/AESC.py &
python3 /home/ubuntu/Desktop/servante/AESC.py &
python3 /home/ubuntu/Desktop/servante/AEVA.py &
python3 /home/ubuntu/Desktop/servante/AESE.py &
python3 /home/ubuntu/Desktop/servante/AEY.py &
python3 /home/ubuntu/Desktop/servante/AEYE.py &
python3 /home/ubuntu/Desktop/servante/AEZS.py &
python3 /home/ubuntu/Desktop/servante/AFAC.py &
python3 /home/ubuntu/Desktop/servante/AFACW.py &
python3 /home/ubuntu/Desktop/servante/AFAQ.py &
python3 /home/ubuntu/Desktop/servante/AFAQU.py &
python3 /home/ubuntu/Desktop/servante/AFAQW.py &
python3 /home/ubuntu/Desktop/servante/AFB.py &
python3 /home/ubuntu/Desktop/servante/AFBI.py &
python3 /home/ubuntu/Desktop/servante/AFCG.py &
python3 /home/ubuntu/Desktop/servante/AFG.py &
python3 /home/ubuntu/Desktop/servante/AFGB.py &
python3 /home/ubuntu/Desktop/servante/AFGC.py &
python3 /home/ubuntu/Desktop/servante/AFGD.py &
python3 /home/ubuntu/Desktop/servante/AFGE.py &
python3 /home/ubuntu/Desktop/servante/AFI.py &
python3 /home/ubuntu/Desktop/servante/AFIB.py &
python3 /home/ubuntu/Desktop/servante/AFL.py &
python3 /home/ubuntu/Desktop/servante/AFMD.py &
python3 /home/ubuntu/Desktop/servante/AFRM.py &
python3 /home/ubuntu/Desktop/servante/AFT.py &
python3 /home/ubuntu/Desktop/servante/AFTR.py &
python3 /home/ubuntu/Desktop/servante/AFYA.py &
python3 /home/ubuntu/Desktop/servante/AG.py &
python3 /home/ubuntu/Desktop/servante/AGAC.py &
python3 /home/ubuntu/Desktop/servante/AGBA.py &
python3 /home/ubuntu/Desktop/servante/AGBAR.py &
python3 /home/ubuntu/Desktop/servante/AGBAW.py &
python3 /home/ubuntu/Desktop/servante/AGCB.py &
python3 /home/ubuntu/Desktop/servante/AGCO.py &
python3 /home/ubuntu/Desktop/servante/AGD.py &
python3 /home/ubuntu/Desktop/servante/AGE.py &
python3 /home/ubuntu/Desktop/servante/AGEN.py &
python3 /home/ubuntu/Desktop/servante/AGFS.py &
python3 /home/ubuntu/Desktop/servante/AGFY.py &
python3 /home/ubuntu/Desktop/servante/AGGR.py &
python3 /home/ubuntu/Desktop/servante/AGGRU.py &
python3 /home/ubuntu/Desktop/servante/AGI.py &
python3 /home/ubuntu/Desktop/servante/AGIL.py &
python3 /home/ubuntu/Desktop/servante/AGILW.py &
python3 /home/ubuntu/Desktop/servante/AGIO.py &
python3 /home/ubuntu/Desktop/servante/AGL.py &
python3 /home/ubuntu/Desktop/servante/AGLE.py &
python3 /home/ubuntu/Desktop/servante/AGM.py &
python3 /home/ubuntu/Desktop/servante/AGMH.py &
python3 /home/ubuntu/Desktop/servante/AGNC.py &
python3 /home/ubuntu/Desktop/servante/AGNCM.py &
python3 /home/ubuntu/Desktop/servante/AGNCN.py &
python3 /home/ubuntu/Desktop/servante/AGNCO.py &
python3 /home/ubuntu/Desktop/servante/AGNCP.py &
python3 /home/ubuntu/Desktop/servante/AGO.py &
python3 /home/ubuntu/Desktop/servante/AGR.py &
python3 /home/ubuntu/Desktop/servante/AGRI.py &
python3 /home/ubuntu/Desktop/servante/AGRIW.py &
python3 /home/ubuntu/Desktop/servante/AGRO.py &
python3 /home/ubuntu/Desktop/servante/AGRX.py &
python3 /home/ubuntu/Desktop/servante/AGS.py &
python3 /home/ubuntu/Desktop/servante/AGTC.py &
python3 /home/ubuntu/Desktop/servante/AGTI.py &
python3 /home/ubuntu/Desktop/servante/AGX.py &
python3 /home/ubuntu/Desktop/servante/AGYS.py &
python3 /home/ubuntu/Desktop/servante/AHCO.py &
python3 /home/ubuntu/Desktop/servante/AHG.py &
python3 /home/ubuntu/Desktop/servante/AHH.py &
python3 /home/ubuntu/Desktop/servante/AHI.py &
python3 /home/ubuntu/Desktop/servante/AHPA.py &
python3 /home/ubuntu/Desktop/servante/AHPAU.py &
python3 /home/ubuntu/Desktop/servante/AHPAW.py &
python3 /home/ubuntu/Desktop/servante/AHPI.py &
python3 /home/ubuntu/Desktop/servante/AHRN.py &
python3 /home/ubuntu/Desktop/servante/AHRNU.py &
python3 /home/ubuntu/Desktop/servante/AHT.py &
python3 /home/ubuntu/Desktop/servante/AI.py &
python3 /home/ubuntu/Desktop/servante/AIB.py &
python3 /home/ubuntu/Desktop/servante/AIC.py &
python3 /home/ubuntu/Desktop/servante/AIF.py &
python3 /home/ubuntu/Desktop/servante/AIG.py &
python3 /home/ubuntu/Desktop/servante/AIH.py &
python3 /home/ubuntu/Desktop/servante/AIHS.py &
python3 /home/ubuntu/Desktop/servante/AIKI.py &
python3 /home/ubuntu/Desktop/servante/AIM.py &
python3 /home/ubuntu/Desktop/servante/AIMAU.py &
python3 /home/ubuntu/Desktop/servante/AIMC.py &
python3 /home/ubuntu/Desktop/servante/AIN.py &
python3 /home/ubuntu/Desktop/servante/AINC.py &
python3 /home/ubuntu/Desktop/servante/AINV.py &
python3 /home/ubuntu/Desktop/servante/AIO.py &
python3 /home/ubuntu/Desktop/servante/AIO.py &
python3 /home/ubuntu/Desktop/servante/AIP.py &
python3 /home/ubuntu/Desktop/servante/AIR.py &
python3 /home/ubuntu/Desktop/servante/AIRC.py &
python3 /home/ubuntu/Desktop/servante/AIRG.py &
python3 /home/ubuntu/Desktop/servante/AIRI.py &
python3 /home/ubuntu/Desktop/servante/AIRS.py &
python3 /home/ubuntu/Desktop/servante/AIRT.py &
python3 /home/ubuntu/Desktop/servante/AIRTP.py &
python3 /home/ubuntu/Desktop/servante/AIT.py &
python3 /home/ubuntu/Desktop/servante/AIU.py &
python3 /home/ubuntu/Desktop/servante/AIV.py &
python3 /home/ubuntu/Desktop/servante/AIZ.py &
python3 /home/ubuntu/Desktop/servante/AIZN.py &
python3 /home/ubuntu/Desktop/servante/AJG.py &
python3 /home/ubuntu/Desktop/servante/AJRD.py &
python3 /home/ubuntu/Desktop/servante/AJX.py &
python3 /home/ubuntu/Desktop/servante/AJXA.py &
python3 /home/ubuntu/Desktop/servante/AKA.py &
python3 /home/ubuntu/Desktop/servante/AKAM.py &
python3 /home/ubuntu/Desktop/servante/AKAN.py &
python3 /home/ubuntu/Desktop/servante/AKBA.py &
python3 /home/ubuntu/Desktop/servante/AKIC.py &
python3 /home/ubuntu/Desktop/servante/AKR.py &
python3 /home/ubuntu/Desktop/servante/AKRO.py &
python3 /home/ubuntu/Desktop/servante/AKTS.py &
python3 /home/ubuntu/Desktop/servante/AKTX.py &
python3 /home/ubuntu/Desktop/servante/AKU.py &
python3 /home/ubuntu/Desktop/servante/AKUS.py &
python3 /home/ubuntu/Desktop/servante/AKYA.py &
python3 /home/ubuntu/Desktop/servante/ALB.py &
python3 /home/ubuntu/Desktop/servante/ALBO.py &
python3 /home/ubuntu/Desktop/servante/ALC.py &
python3 /home/ubuntu/Desktop/servante/ALCC.py &
python3 /home/ubuntu/Desktop/servante/ALCO.py &
python3 /home/ubuntu/Desktop/servante/ALDX.py &
python3 /home/ubuntu/Desktop/servante/ALE.py &
python3 /home/ubuntu/Desktop/servante/ALEC.py &
python3 /home/ubuntu/Desktop/servante/ALEX.py &
python3 /home/ubuntu/Desktop/servante/ALF.py &
python3 /home/ubuntu/Desktop/servante/ALFIW.py &
python3 /home/ubuntu/Desktop/servante/ALG.py &
python3 /home/ubuntu/Desktop/servante/ALGM.py &
python3 /home/ubuntu/Desktop/servante/ALGN.py &
python3 /home/ubuntu/Desktop/servante/ALGS.py &
python3 /home/ubuntu/Desktop/servante/ALGT.py &
python3 /home/ubuntu/Desktop/servante/ALHC.py &
python3 /home/ubuntu/Desktop/servante/ALIT.py &
python3 /home/ubuntu/Desktop/servante/ALJJ.py &
python3 /home/ubuntu/Desktop/servante/ALK.py &
python3 /home/ubuntu/Desktop/servante/ALKS.py &
python3 /home/ubuntu/Desktop/servante/ALLE.py &
python3 /home/ubuntu/Desktop/servante/ALLG.py &
python3 /home/ubuntu/Desktop/servante/ALLK.py &
python3 /home/ubuntu/Desktop/servante/ALLO.py &
python3 /home/ubuntu/Desktop/servante/ALLR.py &
python3 /home/ubuntu/Desktop/servante/ALLT.py &
python3 /home/ubuntu/Desktop/servante/ALLY.py &
python3 /home/ubuntu/Desktop/servante/ALNA.py &
python3 /home/ubuntu/Desktop/servante/ALNY.py &
python3 /home/ubuntu/Desktop/servante/ALOR.py &
python3 /home/ubuntu/Desktop/servante/ALORU.py &
python3 /home/ubuntu/Desktop/servante/ALORW.py &
python3 /home/ubuntu/Desktop/servante/ALOT.py &
python3 /home/ubuntu/Desktop/servante/ALPA.py &
python3 /home/ubuntu/Desktop/servante/ALPAW.py &
python3 /home/ubuntu/Desktop/servante/ALPN.py &
python3 /home/ubuntu/Desktop/servante/ALPP.py &
python3 /home/ubuntu/Desktop/servante/ALR.py &
python3 /home/ubuntu/Desktop/servante/ALRM.py &
python3 /home/ubuntu/Desktop/servante/ALRN.py &
python3 /home/ubuntu/Desktop/servante/ALRS.py &
python3 /home/ubuntu/Desktop/servante/ALSA.py &
python3 /home/ubuntu/Desktop/servante/ALSAR.py &
python3 /home/ubuntu/Desktop/servante/ALSAW.py &
python3 /home/ubuntu/Desktop/servante/ALSN.py &
python3 /home/ubuntu/Desktop/servante/ALT.py &
python3 /home/ubuntu/Desktop/servante/ALTG.py &
python3 /home/ubuntu/Desktop/servante/ALTO.py &
python3 /home/ubuntu/Desktop/servante/ALTR.py &
python3 /home/ubuntu/Desktop/servante/ALTU.py &
python3 /home/ubuntu/Desktop/servante/ALTUU.py &
python3 /home/ubuntu/Desktop/servante/ALTUW.py &
python3 /home/ubuntu/Desktop/servante/ALV.py &
python3 /home/ubuntu/Desktop/servante/ALVR.py &
python3 /home/ubuntu/Desktop/servante/ALX.py &
python3 /home/ubuntu/Desktop/servante/ALXO.py &
python3 /home/ubuntu/Desktop/servante/ALYA.py &
python3 /home/ubuntu/Desktop/servante/ALZN.py &
python3 /home/ubuntu/Desktop/servante/AM.py &
python3 /home/ubuntu/Desktop/servante/AMAL.py &
python3 /home/ubuntu/Desktop/servante/AMAM.py &
python3 /home/ubuntu/Desktop/servante/AMAO.py &
python3 /home/ubuntu/Desktop/servante/AMAOW.py &
python3 /home/ubuntu/Desktop/servante/AMAT.py &
python3 /home/ubuntu/Desktop/servante/AMBA.py &
python3 /home/ubuntu/Desktop/servante/AMBC.py &
python3 /home/ubuntu/Desktop/servante/AMBO.py &
python3 /home/ubuntu/Desktop/servante/AMBP.py &
python3 /home/ubuntu/Desktop/servante/AMC.py &
python3 /home/ubuntu/Desktop/servante/AMCI.py &
python3 /home/ubuntu/Desktop/servante/AMCIW.py &
python3 /home/ubuntu/Desktop/servante/AMCR.py &
python3 /home/ubuntu/Desktop/servante/AMCX.py &
python3 /home/ubuntu/Desktop/servante/AMD.py &
python3 /home/ubuntu/Desktop/servante/AME.py &
python3 /home/ubuntu/Desktop/servante/AMED.py &
python3 /home/ubuntu/Desktop/servante/AMEH.py &
python3 /home/ubuntu/Desktop/servante/AMG.py &
python3 /home/ubuntu/Desktop/servante/AMGN.py &
python3 /home/ubuntu/Desktop/servante/AMH.py &
python3 /home/ubuntu/Desktop/servante/AMK.py &
python3 /home/ubuntu/Desktop/servante/AMKR.py &
python3 /home/ubuntu/Desktop/servante/AMLX.py &
python3 /home/ubuntu/Desktop/servante/AMN.py &
python3 /home/ubuntu/Desktop/servante/AMNB.py &
python3 /home/ubuntu/Desktop/servante/AMOT.py &
python3 /home/ubuntu/Desktop/servante/AMOV.py &
python3 /home/ubuntu/Desktop/servante/AMP.py &
python3 /home/ubuntu/Desktop/servante/AMPE.py &
python3 /home/ubuntu/Desktop/servante/AMPG.py &
python3 /home/ubuntu/Desktop/servante/AMPGW.py &
python3 /home/ubuntu/Desktop/servante/AMPH.py &
python3 /home/ubuntu/Desktop/servante/AMPI.py &
python3 /home/ubuntu/Desktop/servante/AMPL.py &
python3 /home/ubuntu/Desktop/servante/AMPS.py &
python3 /home/ubuntu/Desktop/servante/AMPY.py &
python3 /home/ubuntu/Desktop/servante/AMR.py &
python3 /home/ubuntu/Desktop/servante/AMRC.py &
python3 /home/ubuntu/Desktop/servante/AMRK.py &
python3 /home/ubuntu/Desktop/servante/AMRN.py &
python3 /home/ubuntu/Desktop/servante/AMRS.py &
python3 /home/ubuntu/Desktop/servante/AMRX.py &
python3 /home/ubuntu/Desktop/servante/AMS.py &
python3 /home/ubuntu/Desktop/servante/AMSC.py &
python3 /home/ubuntu/Desktop/servante/AMSF.py &
python3 /home/ubuntu/Desktop/servante/AMST.py &
python3 /home/ubuntu/Desktop/servante/AMSWA.py &
python3 /home/ubuntu/Desktop/servante/AMT.py &
python3 /home/ubuntu/Desktop/servante/AMTB.py &
python3 /home/ubuntu/Desktop/servante/AMTD.py &
python3 /home/ubuntu/Desktop/servante/AMTI.py &
python3 /home/ubuntu/Desktop/servante/AMTX.py &
python3 /home/ubuntu/Desktop/servante/AMWD.py &
python3 /home/ubuntu/Desktop/servante/AMWL.py &
python3 /home/ubuntu/Desktop/servante/AMX.py &
python3 /home/ubuntu/Desktop/servante/AMYT.py &
python3 /home/ubuntu/Desktop/servante/AMZN.py &
python3 /home/ubuntu/Desktop/servante/AN.py &
python3 /home/ubuntu/Desktop/servante/ANAB.py &
python3 /home/ubuntu/Desktop/servante/ANAC.py &
python3 /home/ubuntu/Desktop/servante/ANAT.py &
python3 /home/ubuntu/Desktop/servante/ANDE.py &
python3 /home/ubuntu/Desktop/servante/ANEB.py &
python3 /home/ubuntu/Desktop/servante/ANET.py &
python3 /home/ubuntu/Desktop/servante/ANF.py &
python3 /home/ubuntu/Desktop/servante/ANGH.py &
python3 /home/ubuntu/Desktop/servante/ANDE.py &
python3 /home/ubuntu/Desktop/servante/ANEB.py &
python3 /home/ubuntu/Desktop/servante/ANET.py &
python3 /home/ubuntu/Desktop/servante/ANF.py &
python3 /home/ubuntu/Desktop/servante/ANGH.py &
python3 /home/ubuntu/Desktop/servante/ANGHW.py &
python3 /home/ubuntu/Desktop/servante/ANGI.py &
python3 /home/ubuntu/Desktop/servante/ANGN.py &
python3 /home/ubuntu/Desktop/servante/ANGO.py &
python3 /home/ubuntu/Desktop/servante/ANIK.py &
python3 /home/ubuntu/Desktop/servante/ANIP.py &
python3 /home/ubuntu/Desktop/servante/ANIX.py &
python3 /home/ubuntu/Desktop/servante/ANPC.py &
python3 /home/ubuntu/Desktop/servante/ANSS.py &
python3 /home/ubuntu/Desktop/servante/ANTE.py &
python3 /home/ubuntu/Desktop/servante/ANTM.py &
python3 /home/ubuntu/Desktop/servante/ANTX.py &
python3 /home/ubuntu/Desktop/servante/ANVS.py &
python3 /home/ubuntu/Desktop/servante/ANY.py &
python3 /home/ubuntu/Desktop/servante/ANZU.py &
python3 /home/ubuntu/Desktop/servante/ANZUU.py &
python3 /home/ubuntu/Desktop/servante/ANZUW.py &
python3 /home/ubuntu/Desktop/servante/AOD.py &
python3 /home/ubuntu/Desktop/servante/AOGO.py &
python3 /home/ubuntu/Desktop/servante/AOGOW.py &
python3 /home/ubuntu/Desktop/servante/AOMR.py &
python3 /home/ubuntu/Desktop/servante/AON.py &
python3 /home/ubuntu/Desktop/servante/AORT.py &
python3 /home/ubuntu/Desktop/servante/AOS.py &
python3 /home/ubuntu/Desktop/servante/AOSL.py &
python3 /home/ubuntu/Desktop/servante/AOUT.py &
python3 /home/ubuntu/Desktop/servante/AP.py &
python3 /home/ubuntu/Desktop/servante/APA.py &
python3 /home/ubuntu/Desktop/servante/APAC.py &
python3 /home/ubuntu/Desktop/servante/APACW.py &
python3 /home/ubuntu/Desktop/servante/APAM.py &
python3 /home/ubuntu/Desktop/servante/APCA.py &
python3 /home/ubuntu/Desktop/servante/APCX.py &
python3 /home/ubuntu/Desktop/servante/APCXW.py &
python3 /home/ubuntu/Desktop/servante/APD.py &
python3 /home/ubuntu/Desktop/servante/APDN.py &
python3 /home/ubuntu/Desktop/servante/APEI.py &
python3 /home/ubuntu/Desktop/servante/APEN.py &
python3 /home/ubuntu/Desktop/servante/APG.py &
python3 /home/ubuntu/Desktop/servante/APGB.py &
python3 /home/ubuntu/Desktop/servante/APH.py &
python3 /home/ubuntu/Desktop/servante/API.py &
python3 /home/ubuntu/Desktop/servante/APLD.py &
python3 /home/ubuntu/Desktop/servante/APLE.py &
python3 /home/ubuntu/Desktop/servante/APLS.py &
python3 /home/ubuntu/Desktop/servante/APLT.py &
python3 /home/ubuntu/Desktop/servante/APM.py &
python3 /home/ubuntu/Desktop/servante/APMI.py &
python3 /home/ubuntu/Desktop/servante/APMIU.py &
python3 /home/ubuntu/Desktop/servante/APMIW.py &
python3 /home/ubuntu/Desktop/servante/APN.py &
python3 /home/ubuntu/Desktop/servante/APO.py &
python3 /home/ubuntu/Desktop/servante/APOG.py &
python3 /home/ubuntu/Desktop/servante/APP.py &
python3 /home/ubuntu/Desktop/servante/APPF.py &
python3 /home/ubuntu/Desktop/servante/APPH.py &
python3 /home/ubuntu/Desktop/servante/APPHW.py &
python3 /home/ubuntu/Desktop/servante/APPN.py &
python3 /home/ubuntu/Desktop/servante/APPS.py &
python3 /home/ubuntu/Desktop/servante/APRE.py &
python3 /home/ubuntu/Desktop/servante/APRN.py &
python3 /home/ubuntu/Desktop/servante/APSG.py &
python3 /home/ubuntu/Desktop/servante/APT.py &
python3 /home/ubuntu/Desktop/servante/APTMU.py &
python3 /home/ubuntu/Desktop/servante/APTMW.py &
python3 /home/ubuntu/Desktop/servante/APTO.py &
python3 /home/ubuntu/Desktop/servante/APTS.py &
python3 /home/ubuntu/Desktop/servante/APTV.py &
python3 /home/ubuntu/Desktop/servante/APTX.py &
python3 /home/ubuntu/Desktop/servante/APVO.py &
python3 /home/ubuntu/Desktop/servante/APWC.py &
python3 /home/ubuntu/Desktop/servante/APXI.py &
python3 /home/ubuntu/Desktop/servante/APXIU.py &
python3 /home/ubuntu/Desktop/servante/APXIW.py &
python3 /home/ubuntu/Desktop/servante/APYX.py &
python3 /home/ubuntu/Desktop/servante/AQB.py &
python3 /home/ubuntu/Desktop/servante/AQMS.py &
python3 /home/ubuntu/Desktop/servante/AQN.py &
python3 /home/ubuntu/Desktop/servante/AQNA.py &
python3 /home/ubuntu/Desktop/servante/AQNB.py &
python3 /home/ubuntu/Desktop/servante/AQNU.py &
python3 /home/ubuntu/Desktop/servante/AQST.py &
python3 /home/ubuntu/Desktop/servante/AQUA.py &
python3 /home/ubuntu/Desktop/servante/AR.py &
python3 /home/ubuntu/Desktop/servante/ARAV.py &
python3 /home/ubuntu/Desktop/servante/ARAY.py &
python3 /home/ubuntu/Desktop/servante/ARBE.py &
python3 /home/ubuntu/Desktop/servante/ARBEW.py &
python3 /home/ubuntu/Desktop/servante/ARBG.py &
python3 /home/ubuntu/Desktop/servante/ARBGU.py &
python3 /home/ubuntu/Desktop/servante/ARBGW.py &
python3 /home/ubuntu/Desktop/servante/ARBK.py &
python3 /home/ubuntu/Desktop/servante/ARC.py &
python3 /home/ubuntu/Desktop/servante/%launcher%


